# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Twilt::Perl"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

session: "YAML"

plugins:
  "Auth::Twitter":
    consumer_key:     "qIiB3lLryPtzfgh8sVMI665US"
    consumer_secret:  "w0YWNIfWZyeGX2dGAKr94Xdcsppl7DB1xw8zDKzSHYWzqP9iHM"
    callback_url:     "http://0.0.0.0:3000/auth/twitter/callback"
    callback_success: "/"
    callback_fail:    "/fail"
    ssl:              1
